export const API_PATH_INPUT = 'API_PATH_INPUT';
export const API_XKEY_INPUT = 'API_XKEY_INPUT';
export const SUBMIT_API_CONFIG = 'SUBMIT_API_CONFIG';

export const DOTS_MENU = 'DOTS_MENU';
export const DOTS_MENU_CLEAR_CONFIG = 'DOTS_MENU_CLEAR_CONFIG';