export const BOOKMARKS_SS_K = "BOOKMARKS_SYNC_STORAGE_KEY";
export const API_CONFIG_SS_K = "API_CONFIG_SYNC_STORAGE_KEY";
export const API_PATH_SS_K = "API_PATH_SS_K";
export const API_XKEY_SS_K = "API_XKEY_SS_K";